### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by JamesMichealJohnson** [okvik/ham#1]
I am confused what this is? Could you please explain?

**Comment by okvik** [comment]
It's a Plan 9 (9front) sam/term with changes that make the editor more
convenient for my own use but likely to piss off at least some of the
users who like and rely on old behaviours.  Therefore this personal
soft fork to make the changes available for others to use.

In retrospect I should have provided these as patches, but that's more
work than I can be bothered to put in at this moment. :)

I think the only two changes that may be interesting are the modified
windowing and menu operations, and the removal (more like short-circuiting)
of the separate snarf buffer. Other stuff is pointless bikeshedding.
